ASSETS_FOLDER_NAME = "assets"
PIPE_FITTINGS_OPTIONS_FILE_NAME = "pipe_fitting_options.csv"
PUMP_CURVE_TEMPLATE_FILE_NAME = "pump_curve_template.csv"
PUMP_CURVE_HEAD_COLUMN_NAME = "H"
PUMP_CURVE_VOLUMETRIC_FLOW_COLUMN_NAME = "Q"
SOLVER_DEFAULT_METHOD = "lm"
GRAVITY = 9.81 # meter/second^2